---
name: "sast"

on:
    pull_request: {}
    push:
        branches:
            - "main"
    schedule:
        - cron: "19 19 * * 4"

jobs:
    snyk:
        runs-on: "ubuntu-latest"
        # Snyk will already run on PRs as its own check, only looking at the changed
        # dependencies instead of unchanged ones as this job will do.
        if: github.event_name != 'pull_request'

        steps:
            - uses: "actions/checkout@v3"
            - uses: "pnpm/action-setup@v2.0.1"
              with:
                  version: "latest"
            - uses: "actions/setup-node@v2"
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"
            - uses: "snyk/actions/setup@master"
            - run: "make install"
            - run: "snyk test --all-projects --detection-depth=1"
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
